spring.application.name=${PROJECT_NAME}

#SERVER
server.address=0.0.0.0
server.port=${PORT:8080}

# LOGGING
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
#logging.level.org.flywaydb=INFO
logging.level.com.soondevjomer.libraryverse=INFO

#DATABASE
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

#JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION_MS}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION_MS}

#FILE
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_FILE_SIZE_REQ}

#OTHERS
spring.jpa.open-in-view=false

# FLYWAY
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true
#spring.flyway.clean-disabled=true
#pring.flyway.validate-on-migrate=true


